apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-users-hpa
  namespace: chessquery
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-users
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: { type: Utilization, averageUtilization: 70 }
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-tournament-hpa
  namespace: chessquery
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-tournament
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: { type: Utilization, averageUtilization: 70 }
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-game-hpa
  namespace: chessquery
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-game
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: { type: Utilization, averageUtilization: 70 }
